export const GET_ALLLEMPRENDIMIENTOS_START = 'GET_ALLEMPRENDIMIENTOS_START'
export const GET_ALLEMPRENDIMIENTOS_ERROR = 'GET_ALLEMPRENDIMIENTOS_ERROR'
export const GET_ALLEMPRENDIMIENTOS_COMPLETE = 'GET_ALLEMPRENDIMIENTOS_COMPLETE'

export const getEmprendimiento = () => ({
    type: GET_ALLLEMPRENDIMIENTOS_START
})
